output_dir: 'lib'
js:
  app:
    files:
      - 'src/scripts/core/ui.core.js'
      - 'src/scripts/core/ui.class.js'
      - 'src/scripts/core/ui.eventManager.js'
      - 'src/scripts/core/ui.elem.js'
      - 'src/scripts/core/ui.array.js'
      - 'src/scripts/core/ui.browser.js'
      - 'src/scripts/core/ui.ready.js'
      - 'src/scripts/core/ui.resize.js'
      - 'src/scripts/core/ui.constants.js'
      - 'src/scripts/core/ui.template.js'
  app.utils:
    files:
      - 'src/scripts/utils/ui.querystring.js'
      - 'src/scripts/utils/ui.perftest.js'
  app.mvc:
    inherit: 'app'
    files:
      - 'src/scripts/mvc/ui.controller.js'
      - 'src/scripts/mvc/ui.pageController.js'
      - 'src/scripts/mvc/ui.dataProvider.js'
      - 'src/scripts/mvc/ui.view.js'
      - 'src/scripts/mvc/ui.model.js'
  app.lawnchair:
    inherit: 'app.mvc'
    files:
      - 'external/lawnchair/src/adaptors/WebkitSQLiteAdaptor.js'
      - 'external/lawnchair/src/Lawnchair.js'
      - 'external/lawnchair/src/adaptors/LawnchairAdaptorHelpers.js'
      - 'src/scripts/mvc/ui.lawnchairModelData.js'
  app.mobile:
    inherit: 'app.lawnchair'
    files:
      - 'src/scripts/mobile/ui.mobile.core.js'
  app.sortable:
    files:
      - 'src/scripts/mvc/ui.sortableController.js'
